# Generated by Django 6.0.5 on 2026-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget_allocated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('projects_count', models.IntegerField(default=0)),
            ],
        ),
    ]
