# Generated by Django 6.0.5 on 2026-06-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('stalled', 'Stalled'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='counties.county')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_awarded', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_awarded', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='counties.county')),
            ],
        ),
    ]
